import numpy as np
import matplotlib.pyplot as pyplot

fig, ax = plt.subplots(figsize=(12,6))

#setting up Planck's law
h = 6.63e-34
c = 3.00e8
k = 1.38e-23
x = np.linspace(1e-9, 3e-6, 1000)
temps = np.array([3000,4000,5000,6000])
exp = (h*c)/(x[:, None]*k*temps) #formula generated by Gemini
y = ((2*h*c**2)/(x[:,None]**5))*(1/np.exp(exp)-1))

plt.plot(x*1e-9,y)
plt.xlabel("Wavelength (nm)")
plt.ylabel("Spectral Radiance")
plt.show()
